apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: passgen-home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: passwordgen
  labels: 
    app: passwordgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passwordgen
  template:
    metadata:
      labels:
        app: passwordgen
    spec:
      containers:
      - name: passwordgen
        image: gcr.io/speedy-victory-198818/passwordgen
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: passwordgen
spec:
  selector:
    app: passwordgen
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
